# https://taskfile.dev/

version: "3"

tasks:
  clean:
    desc: Clean
    cmds:
      - go clean

  build:
    desc: Build
    cmds:
      - go build

  linter:install:
    desc: Install linter
    cmds:
      - go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest

  lint:
    desc: Lint the project
    deps:
      - linter:install
    cmds:
      - golangci-lint run

  test:clean:
    desc: Clean test cache
    cmds:
      - go clean -testcache
      - rm -f coverage.out

  test:
    desc: Run tests with verbose flag
    deps:
      - test:clean
    cmds:
      - go test ./...

  test:codecov:
    desc: Run tests for codecov reporting
    cmds:
      - go test -v ./... -coverprofile=coverage.txt

  test:verbose:
    desc: Run tests
    deps:
      - test:clean
    cmds:
      - go test -v ./... -coverprofile=coverage.out

  test:race:
    desc: Run tests with race flag
    deps:
      - test:clean
    cmds:
      - go test -race -v  ./...

  test:cover:
    desc: Run tests with coverage
    cmds:
      - go test ./... -cover

  test:coverprofile:
    desc: Run tests with coverage profile
    cmds:
      - go test ./... -v -coverprofile=coverage.out

  test:cover:report:
    desc: Show coverage
    deps:
      - test:coverprofile
    cmds:
      - go tool cover -html=coverage.out

  ci:
    desc: Run CI
    cmds:
      - task: build
      - task: lint
      - task: test:race
      - task: test:coverprofile
